(assert-exception ProgramException (let (('x 2)) x))